### ISSUE TITLE
Add new VDO CMD commands to have Varbase ready Automated testing builds, install, then run tests using open browser or headless 

### ISSUE THREAD

**Issue by Natshah** [webship/vdo-project#50]
The help for this set of commands
```
rajab@vardot-dev:/var/www/html/test$ bash cmd-vdo-automated-testing-varbase9-1-x-project.sh -h
usage: cmd-vdo-automated-testing-varbase9-1-x-project.sh [-h] [-r] [-b] [-l]
                                                         [-n] [-s]
                                                         PROJECT_NAME
                                                         [TESTING_PATH]

Add new Varbase 9.1.x-dev ready Automated testing builds, and install. Then run
tests using a real browser or headless browser

positional arguments:
  PROJECT_NAME          The name of the project.
  TESTING_PATH          Testing path. default value [ tests/features/varbase ]

optional arguments:
  -h, --help            show this help message and exit
  -r, --run             Run the automate test with real browser. Shows the
                        work of the driver on the browser.
  -b, --run-no-headless
                        Run a real no headless browser automate test. An alies
                        for --run
  -l, --run-headless    Run a headless automate test. Hides the work of the
                        driver on the browser.
  -n, --no-headless     Configure the test as a real browser with no headless
                        automate test.
  -s, --headless        Configure the test as a headless automate test.
```

vdo.settings.yml file should be changed to

```
vdo:
  root: /var/www/html
  path: /var/www/html/vdo
  scripts: /var/www/html/vdo/scripts
  config: /var/www/html/vdo/config
  host: r-natshah.dev.in.vardot.com
  web: http://r-natshah.dev.in.vardot.com/vdo
  backups: /var/www/html/backups
database:
  username: root
  password: 123___
  host: localhost
  port: 3306
  namespace: Drupal\\Core\\Database\\Driver\\mysql
  driver: mysql
  collation: utf8mb4_general_ci
account:
  name: webmaster
  pass: d
  mail: webmaster@vardot.com
config_sync_directory: ../config/sync
automated_testing:
  wd_host: robot7.dev.in.vardot.com:4445/wd/hub
workspaces:
  - products
  - dev
  - test
  - demos
  - sandboxes
  - profiles
  - modules
  - themes
  - libraries
  - forked
```

Change directory to test
```
cd /var/www/html/test/
```

### Run the following command for example
```
bash cmd-vdo-automated-testing-varbase9-0-0-project.sh varbase90v1test1 --run
bash cmd-vdo-automated-testing-varbase9-0-x-project.sh varbase90x1test1 --run
bash cmd-vdo-automated-testing-varbase9-1-0-project.sh varbase91v1test1 --run
bash cmd-vdo-automated-testing-varbase9-1-x-project.sh varbase91x1test1 --run
```
They are for the latest development work on Varbase 9.1.x-dev and latest release tag.
And same for Varbase 9.0.x-dev and the latest release tag.

Add `--run` to run the test after build and install directly 
you can add a path for a selected test folder or file.

-----------------------------------------
 ### Change directory to the project:
```
 cd /var/www/html/test/varbase91x1test1/docroot/profiles/varbase
```
-----------------------------------------
 ### To run the full test with one command:
```
 bash cmd-vdo-automated-testing-varbase9-1-x-project.sh varbase91x1test1 --run tests/features/varbase
```
-----------------------------------------
 ### To run tests in groups
```
 bash cmd-vdo-automated-testing-varbase9-1-x-project.sh varbase91x1test1 --run --testing-path tests/features/varbase/01-website-base-requirements
```
-----------------------------------------
 ### To run only one feature 
```
 bash cmd-vdo-automated-testing-varbase9-1-x-project.sh varbase91x1test1 --run --testing-path tests/features/varbase/01-website-base-requirements/01-01-user-registration_only-admins-login.feature
```
-----------------------------------------

To full test the latest work on Varbase 9.1.x-dev with one command.
```
bash cmd-vdo-automated-testing-varbase9-1-x-project.sh varbase91x1test1 --run
```
